# 空欄を入力したい場合は '' を入力してください

item:
  # hide/showを切り替える際 アイテムも入れ替えるか設定できます。
  # falseの場合は hide/showどちらののアイテムでも show/hideを切り替えられます。
  change_item: false

  ## アイテムの判別にnameとidを用います。
  ## nameが空白の場合は デフォルトの名前（時計なら”時計”） で反応します。
  hide:
    id: WATCH
    name: なんかすごい時計
    lore: §7プレイヤーの §a表示§7/§c非表示 §7を切り替えられる なんかすごいアイテムだよ!

  show:
    id: COMPASS
    name: なんかすごいコンパス
    lore: §7プレイヤーの §a表示§7/§c非表示 §7を切り替えられる なんかすごいアイテムだよ!

## 単位は秒。 0.0でもいいよん
interval: 0.5

## サーバー参加時にアイテムを自動的に配布するかどうか
give_item: true


## 空欄にすればメッセージは送信されません。
message:
  # 接頭辞。メッセージの最初についてるやつ
  prefix:
    success: §2H§aide§2P§alayer §2>> §a
    warning: §6H§eide§6P§elayer §6>> §e
    error: §4H§cide§4P§clayer §4>> §c

  # プレイヤーを消すときのメッセージ
  hide: §r§2§lhid §r§aall players
  show: §r§2§lshowed §r§aall players

  already_hide: already hidden all players =)
  already_show: already shown all players =)

  # intervalは `%s` で参照できます。
  interval: please wait %s seconds ...

  # チェストとかにアイテム入れようとしたときに表示されるメッセージ (adventureのみ)
  inventory_change: please move items in your inventory (press E)